config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'ask', to: 'questions#ask', as: :ask
  get 'answer', to: 'questions#answer', as: :answer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end

  def answer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<h1>Stupid Coaching</h1>
<div>
  <% input = params[:question] %>
  <% if input == "I am going to work" %>
    <%= p "Great!" %>
  <% elsif input.include? "?" %>
    <%= p "Silly question, get dressed and go to work!" %>
  <% else %>
    <%= p "I don't care, get dressed and go to work!" %>
  <% end %>
</div>


<%= link_to "Ask anything to your coach", ask_path %>

app/views/questions/ask.html.erb
<h1>Stupid Coaching</h1>

<form action="answer" method="get">
  <div class="form-group">
    <label for="questionInput">Ask anything to your coach</label>
    <br>
    <br>
    <input type="text" class="btn btn-primary" name="question" placeholder="Type your question">
  </div>
  <br>
  <br>
  <button type="submit" class="btn btn-primary" value="Ask!">Ask!</button>
</form>